
name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: rachitpmsl
        password: Rachit@55!

    - name: Build Docker image
      run: |
        docker build --file Dockerfile --tag rachitpmsl/api:${{ github.sha }} .
        docker push rachitpmsl/api:${{ github.sha }}
    - name: Set up kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl
    
    - name: Deploy to local Kubernetes
      run: |
        ls ./
        kubectl apply -f Django-API/Django-API/manifest
    - name: Get LoadBalancer IP
      run: |
        kubectl get nodes
      id: lb_ip