
name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build --file Dockerfile --tag ${{ secrets.REGISTRY_NAME }}/api:${{ secrets.ACCESS_TOKEN }} .
        docker push ${{ secrets.REGISTRY_NAME }}/api:${{ secrets.ACCESS_TOKEN }}

    - name: Deploy to Kubernetes
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        namespace: default
      env:
        IMAGE: ${{ secrets.REGISTRY_NAME }}/api:${{ github.sha }}
        NAME: api
        run: |
          kubectl set image deployment/${{ env.NAME }} ${env.NAME}=${env.IMAGE} --record
