
name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: rachitpmsl
        password: Rachit@55!

    - name: Build Docker image
      run: |
        docker build --file Dockerfile --tag rachitpmsl/api:${{ github.sha }} .
        docker push rachitpmsl/api:${{ github.sha }}

    - name: Deploy to Kubernetes
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      env:
        IMAGE: rachitpmsl/api:${{ github.sha }}
        NAME: api
        run: |
          kubectl set image deployment/${{ env.NAME }} ${env.NAME}=${env.IMAGE} --record
          kubectl apply -f Django-API/manifests
